### ISSUE TITLE
Stream for particular device?

### ISSUE THREAD

**Issue by stephenjamieson** [kstep/pushybullet#12]
Is there a way to only get items from the stream that are for particular devices?

**Comment by kstep** [comment]
Just use `api.pushes()` method and filter by device iden:
```python
device_iden = "abcdefg"
pushes = (p for p in api.pushes() if p.source_device_iden == device_iden)
```

**Comment by stephenjamieson** [comment]
That's what I thought, wasn't sure if there was something in the API to allow for a single devices pushes besides filtering.  Thanks!
